[package]
name = "rvcs"
version = "0.1.0"
edition = "2021"


[dependencies]
colored = "2.0"
clap = { version = "4.5", features = ["derive","cargo"] }
sha1 = "0.10.6"
flate2 = "1.0"
anyhow = "1.0.93"
regex = "1.11"
glob = "0.3.1"
